import { Product } from './product';

export const PRODUCTS: any[] = [
 {
   id : 1,
   menuCategory: "Baby",
   menuSubCategory: "Baby Chairs",
   dept: "CHILDRENS IKEA",
   deptCategory: "Highchairs",
   imgFilename: "0610892_PE685158_S3.JPG",
   imgFilename2: "antilop-highchair-with-tray-blue__0610892_PE685158_S4.JPG",
   name: "ANTILOP",
   desc: "Highchair with tray, light blue, silver-colour",
   price: 29.9,
   field11: "",
   color: "",
   salesArg: "ANTILOP highchair is easy to take apart and bring along so your child sits safely and steadily whether you are at home, at your friend’s place or at the restaurant. Enjoy your meal!"
 },
 {
   id : 2,
   menuCategory: "Baby",
   menuSubCategory: "Baby Chairs",
   dept: "CHILDRENS IKEA",
   deptCategory: "Highchairs",
   imgFilename: "0371815_PE552123_S3.JPG",
   imgFilename2: "blames-highchair-with-tray-black__0371815_PE552123_S4.JPG",
   name: "BLAMES",
   desc: "Highchair with tray, black",
   price: 79,
   field11: "",
   color: "",
   salesArg: "Even the youngest family member needs a seat at the table. Our highchairs go through the toughest safety testing in the world so you can be sure your child is sitting safe and steady. Enjoy your meal!"
 },
 {
   id : 3,
   menuCategory: "Baby",
   menuSubCategory: "Baby Chairs",
   dept: "CHILDRENS IKEA",
   deptCategory: "Highchairs",
   imgFilename: "0569715_PE666447_S3.JPG",
   imgFilename2: "langur-junior-highchair-white__0569715_PE666447_S4.JPG",
   name: "LANGUR",
   desc: "Junior/highchair with tray, white",
   price: 239,
   field11: "",
   color: "",
   salesArg: "A highchair makes it easier for small children to sit at the same table as adults, which helps them develop social and eating skills."
 },
 {
   id : 4,
   menuCategory: "Baby",
   menuSubCategory: "Baby Chairs",
   dept: "CHILDRENS IKEA",
   deptCategory: "Highchairs",
   imgFilename: "0598333_PE677584_S3.JPG",
   imgFilename2: "langur-junior-highchair-grey__0598333_PE677584_S4.JPG",
   name: "LANGUR",
   desc: "Junior/highchair, grey",
   price: 239,
   field11: "",
   color: "",
   salesArg: "A highchair makes it easier for small children to sit at the same table as adults, which helps them develop social and eating skills."
 },
 {
   id : 5,
   menuCategory: "Baby",
   menuSubCategory: "Baby Chairs",
   dept: "CHILDRENS IKEA",
   deptCategory: "Highchairs",
   imgFilename: "0595090_PE677572_S3.JPG",
   imgFilename2: "langur-seat-shell-for-highchair-grey__0595090_PE677572_S4.JPG",
   name: "LANGUR",
   desc: "Seat shell for highchair, grey",
   price: 80,
   field11: "",
   color: "",
   salesArg: "The included safety belt has been designed so it won’t pinch children when securing them in the highchair, and it has a release button which makes it easy for you – and not your child – to unlock the safety belt with 1 hand."
 },
 {
   id : 6,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0514141_PE639326_S3.JPG",
   imgFilename2: "langur-padded-seat-cover-for-highchair-yellow__0514141_PE639326_S4.JPG",
   name: "LANGUR",
   desc: "Padded seat cover for highchair, yellow",
   price: 20,
   field11: "",
   color: "",
   salesArg: "The padded material relieves pressure on the child’s body and is soft and comfortable to sit on and lean against."
 },
 {
   id : 7,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "70457_PE185756_S3.JPG",
   imgFilename2: "sniglar-cot__70457_PE185756_S4.JPG",
   name: "SNIGLAR",
   desc: "Cot, beech",
   price: 79,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 8,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0551571_PE658682_S3.JPG",
   imgFilename2: "solgul-cot-white__0551571_PE658682_S4.JPG",
   name: "SOLGUL",
   desc: "Cot, white",
   price: 129,
   field11: "",
   color: "",
   salesArg: "When we created the traditional SOLGUL series, we focused on safety. That´s why all the surfaces of the cot, changing table and wardrobe are non-toxic – with all edges and corners softly rounded."
 },
 {
   id : 9,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "70462_PE185759_S3.JPG",
   imgFilename2: "gulliver-cot-white__70462_PE185759_S4.JPG",
   name: "GULLIVER",
   desc: "Cot, white",
   price: 199,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 10,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0124902_PE282087_S3.JPG",
   imgFilename2: "sundvik-cot-brown__0124902_PE282087_S4.JPG",
   name: "SUNDVIK",
   desc: "Cot, grey-brown",
   price: 249,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 11,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0249751_PE388097_S3.JPG",
   imgFilename2: "gonatt-cot-grey__0249751_PE388097_S4.JPG",
   name: "GONATT",
   desc: "Cot, light grey",
   price: 349,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 12,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0455027_PE603158_S3.JPG",
   imgFilename2: "stuva-folja-cot-with-drawers-white__0455027_PE603158_S4.JPG",
   name: "STUVA / FOLJA",
   desc: "Cot with drawers, white",
   price: 344,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 13,
   menuCategory: "Baby",
   menuSubCategory: "Cots",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0590426_PE673875_S3.JPG",
   imgFilename2: "stuva-fritids-cot-with-drawers__0590426_PE673875_S4.JPG",
   name: "STUVA / FRITIDS",
   desc: "Cot with drawers, blackboard surface",
   price: 349,
   field11: "",
   color: "",
   salesArg: "Whether sleeping peacefully or crying to be picked up, an IKEA cot will keep your little one safe and sound. Safety is important, which is why we test our cots to the strictest safety standards in the world."
 },
 {
   id : 14,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0561642_PE663066_S3.JPG",
   imgFilename2: "godmorgon-tolken-gutviken-wsh-stnd-w-countertop-wash-basin-white__0561642_PE663066_S4.JPG",
   name: "GODMORGON/ TOLKEN / GUTVIKEN",
   desc: "Wsh-stnd w countertop 29 wash-basin, high-gloss white, bamboo",
   price: 355,
   field11: "",
   color: "",
   salesArg: "Rise and shine. The high gloss finish is easy to wipe and keep clean, and it creates a fresh expression in the bathroom. Guaranteed to outlast at least 10 years of splashes and steamy showers."
 },
 {
   id : 15,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0421217_PE577754_S3.JPG",
   imgFilename2: "hemnes-hagaviken-wash-stand-with-drawers-white__0421217_PE577754_S4.JPG",
   name: "HEMNES / HAGAVIKEN",
   desc: "Wash-stand with 2 drawers, white",
   price: 350,
   field11: "",
   color: "",
   salesArg: "Since the wash-stand is only 32 cm deep, it takes up little space and leaves more room for you. It also has spacious drawers which give you lots of storage space for things big and small."
 },
 {
   id : 16,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0488939_PE623363_S3.JPG",
   imgFilename2: "lillangen-viskan-gutviken-washbasin-cabinet-with-door-white__0488939_PE623363_S4.JPG",
   name: "LILLÅNGEN/ VISKAN / GUTVIKEN",
   desc: "Washbasin cabinet with 1 door, white, grey",
   price: 213.9,
   field11: "",
   color: "",
   salesArg: "You can place the wash-basin where you prefer – left, right or in the middle."
 },
 {
   id : 17,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0419445_PE576293_S3.JPG",
   imgFilename2: "lillangen-washbasin-cabinet-with-door-white__0419445_PE576293_S4.JPG",
   name: "LILLÅNGEN",
   desc: "Washbasin cabinet with 1 door, white",
   price: 219.9,
   field11: "",
   color: "",
   salesArg: "May be used as a shelf for a soap dish and toothbrush mug, thanks to the depth of the frame."
 },
 {
   id : 18,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0557846_PE661031_S3.JPG",
   imgFilename2: "godmorgon-rattviken-wash-stand-with-drawers-white__0557846_PE661031_S4.JPG",
   name: "GODMORGON / RÄTTVIKEN",
   desc: "Wash-stand with 2 drawers, Kasjön white",
   price: 440,
   field11: "",
   color: "",
   salesArg: "Plain elegance with a matte finish that hides fingerprints and splash marks. Spacious and soft-closing, solid wood drawers. Guaranteed to outlast at least 10 years of splashes and steamy showers."
 },
 {
   id : 19,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0576943_PE668445_S3.JPG",
   imgFilename2: "lillangen-washbasin-cab-door-end-units-white__0576943_PE668445_S4.JPG",
   name: "LILLÅNGEN",
   desc: "Washbasin cab 1 door/2 end units, white, grey",
   price: 289.7,
   field11: "",
   color: "",
   salesArg: "May be used as a shelf for a soap dish and toothbrush mug, thanks to the depth of the frame."
 },
 {
   id : 20,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Stands",
   dept: "BATHROOM",
   deptCategory: "Wash-stands",
   imgFilename: "0485093_PE623929_S3.JPG",
   imgFilename2: "Wsh-stnd w countrtop 45x45 wsh-bsn, black-brown, anthracite",
   name: "GODMORGON/ TOLKEN / TÖRNVIKEN",
   desc: "",
   price: 475,
   field11: "",
   color: "",
   salesArg: "The warm wooden finish and soft-closing solid wood drawers allow you to start the day with a pleasant sense of calm. Guaranteed to outlast at least 10 years of splashes and steamy showers."
 },
 {
   id : 21,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0404548_PE419574_S3.JPG",
   imgFilename2: "hamnviken-single-wash-basin__0404548_PE419574_S4.JPG",
   name: "HAMNVIKEN",
   desc: "Single wash-basin",
   price: 80,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 22,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0380620_PE556373_S3.JPG",
   imgFilename2: "tyngen-single-wash-basin-white__0380620_PE556373_S4.JPG",
   name: "TYNGEN",
   desc: "Single wash-basin, white",
   price: 90,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 23,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0411534_PE236037_S3.JPG",
   imgFilename2: "tornviken-countertop-wash-basin-white__0312264_PE429704_S4.JPG",
   name: "TÖRNVIKEN",
   desc: "Countertop wash-basin, white",
   price: 120,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 24,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0488150_PE639167_S3.JPG",
   imgFilename2: "gutviken-countertop-wash-basin-white__0488150_PE639167_S4.JPG",
   name: "GUTVIKEN",
   desc: "Countertop wash-basin, white",
   price: 80,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 25,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0404616_PE236025_S3.JPG",
   imgFilename2: "odensvik-double-wash-basin__0404616_PE236025_S4.JPG",
   name: "ODENSVIK",
   desc: "Double wash-basin",
   price: 245,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 26,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Wash-Basins",
   dept: "BATHROOM",
   deptCategory: "Wash-basins",
   imgFilename: "0404536_PE302657_S3.JPG",
   imgFilename2: "rattviken-single-wash-basin-white__0404536_PE302657_S4.JPG",
   name: "RÄTTVIKEN",
   desc: "Single wash-basin, white",
   price: 295,
   field11: "",
   color: "",
   salesArg: "Ceramic wash-basins are admired for their smooth, hardwearing beauty. Made with quality materials and the best manufacturing techniques, we proudly offer a 10-year guarantee on all our ceramic wash-basins."
 },
 {
   id : 27,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0558667_PE661634_S3.JPG",
   imgFilename2: "godmorgon-high-cabinet-grey__0558667_PE661634_S4.JPG",
   name: "GODMORGON",
   desc: "High cabinet, Kasjön light grey",
   price: 295,
   field11: "",
   color: "",
   salesArg: "Spacious storage in several beautiful finishes. The soft-closing doors allow you to start the day with a pleasant sense of calm. Guaranteed to outlast at least 10 years of splashes and steamy showers."
 },
 {
   id : 28,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0558517_PE661528_S3.JPG",
   imgFilename2: "godmorgon-high-cabinet-white__0558517_PE661528_S4.JPG",
   name: "GODMORGON",
   desc: "High cabinet, Resjön white",
   price: 295,
   field11: "",
   color: "",
   salesArg: "10 year guarantee. Read about the terms in the guarantee brochure."
 },
 {
   id : 29,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0143673_PE303200_S3.JPG",
   imgFilename2: "hemnes-high-cabinet-with-mirror-door-white__0143673_PE303200_S4.JPG",
   name: "HEMNES",
   desc: "High cabinet with mirror door, white",
   price: 385,
   field11: "",
   color: "",
   salesArg: "You can move the shelves and adjust the spacing according to your personal needs."
 },
 {
   id : 30,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0121046_PE277837_S3.JPG",
   imgFilename2: "lillangen-high-cabinet-brown__0121046_PE277837_S4.JPG",
   name: "LILLÅNGEN",
   desc: "High cabinet, black-brown",
   price: 145,
   field11: "",
   color: "",
   salesArg: "You can mount the door to open from the right or left. Adjustable feet make it possible to compensate any irregularities in the floor."
 },
 {
   id : 31,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0249576_PE387792_S3.JPG",
   imgFilename2: "silveran-corner-unit-brown__0249576_PE387792_S4.JPG",
   name: "SILVERÅN",
   desc: "Corner unit, light brown",
   price: 240,
   field11: "",
   color: "",
   salesArg: "The solid pine shows off the attractive grains and beauty mark knots that give each unique piece its own naturally grown, individual personality."
 },
 {
   id : 32,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "High Cabinets",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0364835_PE548299_S3.JPG",
   imgFilename2: "yddingen-high-cabinet-white__0364835_PE548299_S4.JPG",
   name: "YDDINGEN",
   desc: "High cabinet, white",
   price: 250,
   field11: "",
   color: "",
   salesArg: "Hooks for towels or other things that you want to have within easy reach."
 },
 {
   id : 33,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0458841_PE606078_S3.JPG",
   imgFilename2: "nissedal-mirror-black__0458841_PE606078_S4.JPG",
   name: "NISSEDAL",
   desc: "Mirror, black",
   price: 29.9,
   field11: "",
   color: "",
   salesArg: "The timeless design works just as well in the living room as in the bathroom. Matches nicely with our MALM series."
 },
 {
   id : 34,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0372166_PE552270_S3.JPG",
   imgFilename2: "ikornnes-table-mirror__0372166_PE552270_S4.JPG",
   name: "IKORNNES",
   desc: "Table mirror, ash",
   price: 39.9,
   field11: "",
   color: "",
   salesArg: "This mirror works just as well on a chest of drawers as on a wall. When it’s on the wall you can use the stand to hang your scarves or ties. The soft shapes and warm ash veneer create a cosy feeling."
 },
 {
   id : 35,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0131237_PE285757_S3.JPG",
   imgFilename2: "lillangen-mirror-brown__0131237_PE285757_S4.JPG",
   name: "LILLÅNGEN",
   desc: "Mirror, black-brown",
   price: 45,
   field11: "",
   color: "",
   salesArg: "The mirror comes with safety film on the back, which reduces the risk of injury if the glass is broken."
 },
 {
   id : 36,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0367484_PE549474_S3.JPG",
   imgFilename2: "karmsund-table-mirror-black__0367484_PE549474_S4.JPG",
   name: "KARMSUND",
   desc: "Table mirror, black",
   price: 24.9,
   field11: "",
   color: "",
   salesArg: "You decide the style of this mirror by adding or removing the crown up top. The small tray under the mirror keeps smaller things like jewellery or makeup in place."
 },
 {
   id : 37,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0172866_PE327029_S3.JPG",
   imgFilename2: "isfjorden-standing-mirror__0172866_PE327029_S4.JPG",
   name: "ISFJORDEN",
   desc: "Standing mirror, white stain",
   price: 149,
   field11: "",
   color: "",
   salesArg: "Use the smart little shelf underneath for things like hairdryer or brushes and the knobs on the sides to hang belts and jewellery. A genuine and romantic feeling with straightforward design in solid wood."
 },
 {
   id : 38,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0367487_PE549471_S3.JPG",
   imgFilename2: "karmsund-table-mirror-black__0367487_PE549471_S4.JPG",
   name: "KARMSUND",
   desc: "Table mirror, black",
   price: 59,
   field11: "",
   color: "",
   salesArg: "You decide the style of this mirror by adding or removing the crown up top. The adjustable side mirrors with hooks on the back allow you to see yourself from all angles when fixing your hair or applying makeup."
 },
 {
   id : 39,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Bathroom mirrors",
   imgFilename: "0387958_PE559032_S3.JPG",
   imgFilename2: "saltrod-mirror-with-shelf-and-hooks-white__0387958_PE559032_S4.JPG",
   name: "SALTRÖD",
   desc: "Mirror with shelf and hooks, white",
   price: 79,
   field11: "",
   color: "",
   salesArg: "Grab your scarf, keys and sunglasses and take a final look in the mirror before you leave. Everything is right where you left it on the hooks and shelf."
 },
 {
   id : 40,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Mirror Cabinets",
   imgFilename: "0364826_PE548306_S3.JPG",
   imgFilename2: "brickan-mirror-with-storage-unit-white__0364826_PE548306_S4.JPG",
   name: "BRICKAN",
   desc: "Mirror with storage unit, white",
   price: 89,
   field11: "",
   color: "white",
   salesArg: "Two functions in one – there are shelves behind the mirror for bottles and smaller storage boxes."
 },
 {
   id : 41,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Mirror Cabinets",
   imgFilename: "0558674_PE663410_S3.JPG",
   imgFilename2: "godmorgon-mirror-cabinet-with-doors-grey__0558674_PE663410_S4.JPG",
   name: "GODMORGON",
   desc: "Mirror cabinet with 2 doors, Kasjön light grey",
   price: 325,
   field11: "",
   color: "grey",
   salesArg: "A home for all your toiletries - shallow cabinets make efficient use of your wall space. Mirrors let you see your reflection at all angles. Guaranteed to outlast at least 10 years of splashes and steamy showers."
 },
 {
   id : 42,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Bathroom Mirrors",
   dept: "BATHROOM",
   deptCategory: "Vanity Mirrors",
   imgFilename: "26262_PE092247_S3.JPG",
   imgFilename2: "frack-mirror__26262_PE092247_S4.JPG",
   name: "FRÄCK",
   desc: "Mirror, stainless steel",
   price: 19.9,
   field11: "",
   color: "",
   salesArg: "One side with magnifying mirror glass. Suitable for use in high humidity areas since it is water-resistant."
 },
 {
   id : 43,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0419273_PE576211_S3.JPG",
   imgFilename2: "vesken-shelf-unit-white__0419273_PE576211_S4.JPG",
   name: "VESKEN",
   desc: "Shelf unit, white",
   price: 9.9,
   field11: "",
   color: "",
   salesArg: "Assemble the shelf unit quickly and easily by clicking the parts together without any tools."
 },
 {
   id : 44,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0095663_PE234541_S3.JPG",
   imgFilename2: "molger-shelving-unit__0095663_PE234541_S4.JPG",
   name: "MOLGER",
   desc: "Shelving unit, birch",
   price: 79,
   field11: "",
   color: "",
   salesArg: "The open shelves give an easy overview and easy reach."
 },
 {
   id : 45,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0477185_PE616860_S3.JPG",
   imgFilename2: "algot-wall-upright-shelves-drying-rack-white__0477185_PE616860_S4.JPG",
   name: "ALGOT",
   desc: "Wall upright/shelves/drying rack, white",
   price: 73,
   field11: "",
   color: "",
   salesArg: "A versatile system for the pantry, laundry room or wherever it’s needed. Just click the brackets onto the wall uprights to add a shelf or accessory – it’s easy to add or remove parts as your needs change."
 },
 {
   id : 46,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0469436_PE612248_S3.JPG",
   imgFilename2: "dynan-cabinet-with-door-white__0469436_PE612248_S4.JPG",
   name: "DYNAN",
   desc: "Cabinet with door, white",
   price: 49.9,
   field11: "",
   color: "",
   salesArg: "Tight corners and cramped spaces – almost anything is possible with modular DYNAN series. You can build your storage vertically or horizontally and add on extra shelves to make the most of your space."
 },
 {
   id : 47,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0341869_PE530521_S3.JPG",
   imgFilename2: "kaglan-corner-shelf-white__0341869_PE530521_S4.JPG",
   name: "KÄGLAN",
   desc: "Corner shelf, white",
   price: 16.9,
   field11: "",
   color: "",
   salesArg: "Tight corners and cramped spaces – almost anything is possible with modular DYNAN series. You can build your storage vertically or horizontally and add on extra shelves to make the most of your space."
 },
 {
   id : 48,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Shelf Units",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0484079_PE627790_S3.JPG",
   imgFilename2: "lillangen-end-unit-grey__0484079_PE627790_S4.JPG",
   name: "LILLÅNGEN",
   desc: "End unit, grey",
   price: null,
   field11: "",
   color: "",
   salesArg: "A good solution if you are short of space. The open shelves are perfect for perfume bottles or other things that you use frequently."
 },
 {
   id : 49,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0284759_PE421942_S3.JPG",
   imgFilename2: "bolmen-step-stool-blue__0284759_PE421942_S4.JPG",
   name: "BOLMEN",
   desc: "Step stool, blue",
   price: 7.9,
   field11: "",
   color: "",
   salesArg: "The step stool is suitable for both children and adults as it is tested and approved for a maximum weight capacity of 150 kg."
 },
 {
   id : 50,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0179379_PE331769_S3.JPG",
   imgFilename2: "forsiktig-children-s-stool-green__0179379_PE331769_S4.JPG",
   name: "FÖRSIKTIG",
   desc: "Children's stool, white, green",
   price: 2.9,
   field11: "",
   color: "",
   salesArg: "“Hey! Step up so you can see yourself in the mirror! Now that you can reach the toothbrush you can learn brush your teeth on your own. While you’re at it say ‘hi’ to that grown-up standing next to you.”"
 },
 {
   id : 51,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "26457_PE090792_S3.JPG",
   imgFilename2: "bursjon-stool-with-storage-white__26457_PE090792_S4.JPG",
   name: "BURSJÖN",
   desc: "Stool with storage, white",
   price: 14.9,
   field11: "",
   color: "",
   salesArg: "Vent holes in the bottom. Helps you organise laundry, toys, caps and gloves."
 },
 {
   id : 52,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0589131_PE673308_S3.JPG",
   imgFilename2: "vasteron-stool-in-outdoor-orange__0399339_PE570308_S4.JPG",
   name: "VÄSTERÖN",
   desc: "Stool, in/outdoor, orange",
   price: 17.5,
   field11: "",
   color: "",
   salesArg: "Can be stacked, which helps you save space. Can also be used in bathrooms and other damp areas indoors."
 },
 {
   id : 53,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0242437_PE381827_S3.JPG",
   imgFilename2: "silveran-storage-bench-brown__0242437_PE381827_S4.JPG",
   name: "SILVERÅN",
   desc: "Storage bench, light brown",
   price: 95,
   field11: "",
   color: "",
   salesArg: "The solid pine shows off the attractive grains and beauty mark knots that give each unique piece its own naturally grown, individual personality."
 },
 {
   id : 54,
   menuCategory: "Bathroom Furniture",
   menuSubCategory: "Stool and Benches",
   dept: "BATHROOM",
   deptCategory: "Bathroom storage ",
   imgFilename: "0172862_PE327027_S3.JPG",
   imgFilename2: "molger-bench__0172862_PE327027_S4.JPG",
   name: "MOLGER",
   desc: "Bench, birch",
   price: 55,
   field11: "",
   color: "",
   salesArg: ""
 },
 {
   id : 55,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "08177_PE084938_S3.JPG",
   imgFilename2: "sniglar-changing-table-white__08177_PE084938_S4.JPG",
   name: "SNIGLAR",
   desc: "Changing table, beech, white",
   price: 59,
   field11: "",
   color: "",
   salesArg: "A secure place where you and your baby can get to know one another in peace and quiet. Comfortable height and storage close at hand so you can reach what you need and always keep one hand on the baby."
 },
 {
   id : 56,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0244226_PE383429_S3.JPG",
   imgFilename2: "onsklig-stor-baskets-changing-tbl-set-of-white__0244226_PE383429_S4.JPG",
   name: "ÖNSKLIG",
   desc: "Stor baskets changing tbl set of 4, white",
   price: 15.9,
   field11: "",
   color: "",
   salesArg: "Curious children can become a real challenge at the changing table. There are so many exciting things to discover. This set keeps baby care items out of the way but close at hand."
 },
 {
   id : 57,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0174372_PE328089_S3.JPG",
   imgFilename2: "lattsam-baby-bath-green__0174372_PE328089_S4.JPG",
   name: "LÄTTSAM",
   desc: "Baby bath, white, green",
   price: 15.9,
   field11: "",
   color: "",
   salesArg: "Splish splash – how fun it is with a baby bath! It’s easy to move and place where you want it and it stands steady while your baby discovers the water. The edges are nice and soft, so no one gets hurt."
 },
 {
   id : 58,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0549117_PE657566_S3.JPG",
   imgFilename2: "solgul-changing-table-white__0549117_PE657566_S4.JPG",
   name: "SOLGUL",
   desc: "Changing table, white",
   price: 119,
   field11: "",
   color: "",
   salesArg: "When we created the traditional SOLGUL series, we focused on safety. That´s why all the surfaces of the cot, changing table and wardrobe are non-toxic – with all edges and corners softly rounded."
 },
 {
   id : 59,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0485045_PE621411_S3.JPG",
   imgFilename2: "stuva-folja-changing-table-with-drawers-white__0485045_PE621411_S4.JPG",
   name: "STUVA / FÖLJA",
   desc: "Changing table with 4 drawers, white",
   price: 289,
   field11: "",
   color: "",
   salesArg: "It’s so much more than just a changing table! It grows with your child and easily converts into a play table or desk. It’s a durable piece of furniture that can stay in your home for many years!"
 },
 {
   id : 60,
   menuCategory: "Baby",
   menuSubCategory: "Changing tables & nursing",
   dept: "CHILDRENS IKEA",
   deptCategory: "Baby",
   imgFilename: "0255235_PE399390_S3.JPG",
   imgFilename2: "tovig-baby-bouncer-red__0255235_PE399390_S4.JPG",
   name: "TOVIG",
   desc: "Baby bouncer, blue, red",
   price: 69,
   field11: "",
   color: "",
   salesArg: "Your baby will feel stimulated by watching activities in your home from a safe and comfortable half-sitting position in the baby bouncer."
 },
 {
   id : 61,
   menuCategory: "Cabinets",
   menuSubCategory: "Cabinets & display cabinets",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0560504_PE662379_S3.JPG",
   imgFilename2: "lixhult-storage-combination-white__0560504_PE662379_S4.JPG",
   name: "LIXHULT",
   desc: "Storage combination, white, pink",
   price: 75,
   field11: "",
   color: "",
   salesArg: "Everything you need for storing and keeping things organised at home. Choose a ready-made combination or create your own, adapted to your style and belongings. This is just one of many, many possibilities."
 },
 {
   id : 62,
   menuCategory: "Cabinets",
   menuSubCategory: "Cabinets & display cabinets",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0560506_PE662381_S3.JPG",
   imgFilename2: "lixhult-storage-combination-green__0560506_PE662381_S4.JPG",
   name: "LIXHULT",
   desc: "Storage combination, grey dark green, pink",
   price: 105,
   field11: "",
   color: "",
   salesArg: "Challenge the ordinary! Combine different shapes and sizes, stack and combine, with or without legs, and let loose with a palette of playful colours. Have fun!"
 },
 {
   id : 63,
   menuCategory: "Cabinets",
   menuSubCategory: "Cabinets & display cabinets",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0177049_PE329680_S3.JPG",
   imgFilename2: "fabrikor-glass-door-cabinet-beige__0177049_PE329680_S4.JPG",
   name: "FABRIKÖR",
   desc: "Glass-door cabinet, beige",
   price: 249,
   field11: "",
   color: "",
   salesArg: "With a glass-door cabinet you can show off as well as protect your glassware or your favourite collection."
 },
 {
   id : 64,
   menuCategory: "Cabinets",
   menuSubCategory: "Cabinets & display cabinets",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0552046_PE658842_S3.JPG",
   imgFilename2: "fabrikor-glass-door-cabinet-white__0552046_PE658842_S4.JPG",
   name: "FABRIKÖR",
   desc: "Glass-door cabinet, white",
   price: 249,
   field11: "",
   color: "",
   salesArg: "With a glass-door cabinet you can show off as well as protect your glassware or your favourite collection."
 },
 {
   id : 65,
   menuCategory: "Cabinets",
   menuSubCategory: "Cabinets & display cabinets",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0383562_PE558041_S3.JPG",
   imgFilename2: "malsjo-glass-door-cabinet__0383562_PE558041_S4.JPG",
   name: "MALSJÖ",
   desc: "Glass-door cabinet, black stained",
   price: 499,
   field11: "",
   color: "",
   salesArg: "The glass shelves are adjustable so you can customise your storage as needed."
 },
 {
   id : 66,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "54252_PE158403_S3.JPG",
   imgFilename2: "ikea-ps-cabinet-white__54252_PE158403_S4.JPG",
   name: "IKEA PS",
   desc: "Cabinet, white",
   price: 99,
   field11: "",
   color: "",
   salesArg: "A cord outlet underneath makes it easy to gather all cords in one place."
 },
 {
   id : 67,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0415045_PE574384_S3.JPG",
   imgFilename2: "besta-storage-combination-with-doors__0415045_PE574384_S4.JPG",
   name: "BESTÅ",
   desc: "Storage combination with doors, black-brown, Glassvik black/smoked glass",
   price: 395,
   field11: "",
   color: "black",
   salesArg: "Everything you need for storing and keeping things organised at home. Choose a ready-made combination or create your own, adapted to your style and belongings. This is just one of many, many possibilities."
 },
 {
   id : 68,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0178735_PE331596_S3.JPG",
   imgFilename2: "stockholm-sideboard__0178735_PE331596_S4.JPG",
   name: "STOCKHOLM",
   desc: "Sideboard, walnut veneer",
   price: 799,
   field11: "",
   color: "",
   salesArg: "The sideboard in walnut veneer and solid ash brings a warm, natural feeling to your room."
 },
 {
   id : 69,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0331498_PE523202_S3.JPG",
   imgFilename2: "hemnes-sideboard__0331498_PE523202_S4.JPG",
   name: "HEMNES",
   desc: "Sideboard, white stain",
   price: 499,
   field11: "",
   color: "white",
   salesArg: "Sustainable beauty from sustainably-sourced solid pine, a natural and renewable material that gets more beautiful with each passing year. Like it? Combine with other products in the HEMNES series."
 },
 {
   id : 71,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0442767_PE593930_S3.JPG",
   imgFilename2: "malsjo-sideboard-basic-unit__0442767_PE593930_S4.JPG",
   name: "MALSJÖ",
   desc: "Sideboard basic unit, black stained",
   price: 599,
   field11: "",
   color: "black",
   salesArg: "With a glass-door cabinet you can show off as well as protect your glassware or your favourite collection."
 },
 {
   id : 72,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0260733_PE404589_S3.JPG",
   imgFilename2: "arkelstorp-sideboard-black__0260733_PE404589_S4.JPG",
   name: "ARKELSTORP",
   desc: "Sideboard, black",
   price: 499,
   field11: "",
   color: "black",
   salesArg: "Solid wood is a durable natural material. Adjustable feet; stands steady also on an uneven floor."
 },
 {
   id : 73,
   menuCategory: "Cabinets",
   menuSubCategory: "Buffets & side boards",
   dept: "LIVING ROOM",
   deptCategory: "Living room storage ",
   imgFilename: "0177114_PE329976_S3.JPG",
   imgFilename2: "hemnes-console-table-brown__0177114_PE329976_S4.JPG",
   name: "HEMNES",
   desc: "Console table, black-brown",
   price: 299,
   field11: "",
   color: "brown",
   salesArg: "Natural beauty in solid pine. A durable and renewable material that maintains its genuine character with each passing year. Looks great together with other furniture in the HEMNES series."
 },
 {
   id : 74,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "26018_PE111026_S3.JPG",
   imgFilename2: "tullsta-armchair-beige__26018_PE111026_S4.JPG",
   name: "TULLSTA",
   desc: "Armchair, Ransta natural",
   price: 139,
   field11: "armchair",
   color: "white",
   salesArg: "A range of coordinated covers makes it easy for you to give your furniture a new look."
 },
 {
   id : 75,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0382520_PE557479_S3.JPG",
   imgFilename2: "jennylund-armchair-white__0382520_PE557479_S4.JPG",
   name: "JENNYLUND",
   desc: "Armchair, Stenåsa white",
   price: 325,
   field11: "armchair",
   color: "white",
   salesArg: "A range of coordinated covers makes it easy for you to give your furniture a new look."
 },
 {
   id : 76,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0325450_PE517970_S3.JPG",
   imgFilename2: "strandmon-wing-chair-yellow__0325450_PE517970_S4.JPG",
   name: "STRANDMON",
   desc: "Wing chair, Skiftebo yellow",
   price: 299,
   field11: "Wing chair",
   color: "yellow",
   salesArg: "Bringing new life to an old favourite. We first introduced this chair in the 1950’s. Some 60 years later we brought it back into the range with the same craftsmanship, comfort and appearance. Enjoy!"
 },
 {
   id : 77,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0583605_PE671267_S3.JPG",
   imgFilename2: "agen-chair-yellow__0583605_PE671267_S4.JPG",
   name: "AGEN",
   desc: "Chair, yellow",
   price: 69,
   field11: "",
   color: "yellow",
   salesArg: "The furniture is hand-woven and therefore unique. Stackable; saves space when not in use."
 },
 {
   id : 78,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0571504_PE666937_S3.JPG",
   imgFilename2: "poang-armchair-orange__0571504_PE666937_S4.JPG",
   name: "POÄNG",
   desc: "Armchair, birch veneer, Knisa orange red/orange",
   price: 109,
   field11: "armchair",
   color: "Red",
   salesArg: "Layer-glued bent birch frame gives comfortable resilience. The high back gives good support for your neck."
 },
 {
   id : 79,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0571981_PE667215_S3.JPG",
   imgFilename2: "poang-rocking-chair-orange__0571981_PE667215_S4.JPG",
   name: "POÄNG",
   desc: "Rocking-chair, birch veneer, Knisa orange red/orange",
   price: 209,
   field11: "Rocking-chair",
   color: "Red",
   salesArg: "Layer-glued bent birch frame gives comfortable resilience. The high back gives good support for your neck."
 },
 {
   id : 80,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0568402_PE667162_S3.JPG",
   imgFilename2: "kivik-chaise-longue-red__0568402_PE667162_S4.JPG",
   name: "KIVIK",
   desc: "Chaise longue, Orrsta red",
   price: 405,
   field11: "Fabric chaise longues",
   color: "Red",
   salesArg: "KIVIK is a generous seating series with a soft, deep seat and comfortable support for your back."
 },
 {
   id : 81,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0574496_PE668338_S3.JPG",
   imgFilename2: "delaktig-armchair-blue__0574496_PE668338_S4.JPG",
   name: "DELAKTIG",
   desc: "Armchair, Hillared dark blue",
   price: 779,
   field11: "armchair",
   color: "Blue",
   salesArg: "This is a combination for you if you prefer a classic armchair. But if you still want to feel a little rebellious, you can use different covers for the seat cushion and use armrests/neck support with cushions to make the armchair more personal."
 },
 {
   id : 82,
   menuCategory: "Chairs",
   menuSubCategory: "Armchairs",
   dept: "LIVING ROOM",
   deptCategory: "Sofas & armchairs",
   imgFilename: "0386180_PE559141_S3.JPG",
   imgFilename2: "ektorp-armchair-blue__0386180_PE559141_S4.JPG",
   name: "EKTORP",
   desc: "Armchair, Nordvalla light blue",
   price: 395,
   field11: "armchair",
   color: "Blue",
   salesArg: "Our beloved EKTORP seating has a timeless design and wonderfully thick, comfy cushions. The covers are easy to change, so buy an extra cover - or two, and change according to mood or season."
 },
 {
   id : 83,
   menuCategory: "Chairs",
   menuSubCategory: "Dining Chairs",
   dept: "DINING",
   deptCategory: "Dining Chairs",
   imgFilename: "0174112_PE328016_S3.JPG",
   imgFilename2: "adde-chair-black__0174112_PE328016_S4.JPG",
   name: "ADDE",
   desc: "Chair, black",
   price: 12.5,
   field11: "",
   color: "Black",
   salesArg: "You can stack the chairs, so they take less space when you're not using them."
 },
 {
   id : 84,
   menuCategory: "Chairs",
   menuSubCategory: "Dining Chairs",
   dept: "DINING",
   deptCategory: "Dining Chairs",
   imgFilename: "0094409_PE232293_S3.JPG",
   imgFilename2: "bernhard-chair-white__0094409_PE232293_S4.JPG",
   name: "BERNHARD",
   desc: "Chair, chrome-plated, Kavat Mjuk white",
   price: 150,
   field11: "",
   color: "",
   salesArg: ""
 },
 {
   id : 85,
   menuCategory: "Chairs",
   menuSubCategory: "Dining Chairs",
   dept: "DINING",
   deptCategory: "Dining Chairs",
   imgFilename: "0518606_PE641097_S3.JPG",
   imgFilename2: "martin-chair-black__0518606_PE641097_S4.JPG",
   name: "MARTIN",
   desc: "Chair, black, black",
   price: 35,
   field11: "",
   color: "",
   salesArg: "You can stack the chairs, so they take less space when you're not using them."
 },
 {
   id : 86,
   menuCategory: "Chairs",
   menuSubCategory: "Dining Chairs",
   dept: "DINING",
   deptCategory: "Dining Chairs",
   imgFilename: "0243012_PE382260_S3.JPG",
   imgFilename2: "nisse-folding-chair-orange__0243012_PE382260_S4.JPG",
   name: "NISSE",
   desc: "Folding chair, orange",
   price: 19.9,
   field11: "",
   color: "",
   salesArg: "You can fold the chair, so it takes less space when you're not using it."
 },
 {
   id : 87,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0438287_PE591359_S3.JPG",
   imgFilename2: "stig-bar-stool-with-backrest-black__0438287_PE591359_S4.JPG",
   name: "STIG",
   desc: "Bar stool with backrest, black, silver-colour",
   price: 19.9,
   field11: "",
   color: "",
   salesArg: "The stool can be stacked, so you can keep several on hand and store them on the same space as one."
 },
 {
   id : 88,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0328892_PE520638_S3.JPG",
   imgFilename2: "janinge-bar-stool-grey__0328892_PE520638_S4.JPG",
   name: "JANINGE",
   desc: "Bar stool, grey",
   price: 159,
   field11: "",
   color: "",
   salesArg: "Challenged to solve the equation of combining design, function and quality in one chair, our designers came up with JANINGE chair. Durable enough for restaurant use – with a design you want to take home."
 },
 {
   id : 89,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0101062_PE244903_S3.JPG",
   imgFilename2: "dalfred-bar-stool-black__0101062_PE244903_S4.JPG",
   name: "DALFRED",
   desc: "Bar stool, black",
   price: 69,
   field11: "",
   color: "",
   salesArg: "You can adjust the height as you like."
 },
 {
   id : 90,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0499306_PE630212_S3.JPG",
   imgFilename2: "renberget-swivel-chair-black__0499306_PE630212_S4.JPG",
   name: "RENBERGET",
   desc: "Swivel chair, Bomstad black",
   price: 79,
   field11: "",
   color: "",
   salesArg: "Comfy and lightweight so it’s easy to move about. The castors have a brake mechanism that keeps the chair in place when you stand up, and releases when you sit down – keeping you and your bottom from harm."
 },
 {
   id : 91,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0470188_PE612588_S3.JPG",
   imgFilename2: "millberget-swivel-chair-white__0470188_PE612588_S4.JPG",
   name: "MILLBERGET",
   desc: "Swivel chair, Kimstad white",
   price: 59,
   field11: "",
   color: "",
   salesArg: "This desk chair has adjustable tilt tension that allows you to adjust the resistance to suit your movements and weight."
 },
 {
   id : 92,
   menuCategory: "Chairs",
   menuSubCategory: "Bar Chairs",
   dept: "DINING",
   deptCategory: "Bar tables & chairs",
   imgFilename: "0428767_PE583696_S3.JPG",
   imgFilename2: "orfjall-sporren-swivel-chair-blue__0428767_PE583696_S4.JPG",
   name: "ÖRFJÄLL / SPORREN",
   desc: "Swivel chair, white, Vissle light blue",
   price: 69,
   field11: "",
   color: "",
   salesArg: "High-quality density foam will keep the chair comfortable for many years to come."
 }
];